### ISSUE TITLE
建议在翻译退化后设置frequency_penalty

### ISSUE THREAD

**Issue by jisadn** [cx2333-gt/GalTransl#77]
如出现退化（退化的例子可参见
https://github.com/SakuraLLM/Sakura-13B-Galgame/issues/35
与
https://github.com/SakuraLLM/Sakura-13B-Galgame/issues/36
），可增加frequency_penalty参数，并设置为大于0的某值，一般设置0.1~0.2即可。

**Comment by cx2333-gt** [comment]
https://github.com/cx2333-gt/GalTransl/blob/a183833d3f8422118bd87b3419111b2ff9edadd0/GalTransl/Backend/SakuraTranslate.py#L227
